### ISSUE TITLE
localhost:8080/ontowiki/

### ISSUE THREAD

**Issue by triechert** [AKSW/cpl-compose-leipzig#3]
http://localhost:8080/ontowiki/ forwards to http://localhost/ontowiki/ that will not work.

**Comment by simeonackermann** [comment]
Have you tried to build the containers without cache?

**Comment by triechert** [comment]
yes ontowiki is on now, but login fails

**Comment by GeorgesAlkhouri** [comment]
The problem was the following commit: 

AKSW/cpl-docker@14e955819c5751a193321e2e6b9bd33e73d5350d

The ontowiki-docker could not get the virtuoso password anymore.
Fixed it. 
(AKSW/cpl-docker@b1cdb78355cfb367471f2ff3208e50ecd9dd59f5
AKSW/cpl-docker@6345d887632b7930612ce6918f95c6ab4ec4f37d)
