### ISSUE TITLE
Wrong IP redirecting for editor in d2rq docker

### ISSUE THREAD

**Issue by GeorgesAlkhouri** [AKSW/cpl-compose-leipzig#5]
Look at those two lines here [index.php](https://github.com/AKSW/cpl-docker/blob/master/d2rq-docker/editor/index.php#l41) and here [index.php](https://github.com/AKSW/cpl-docker/blob/master/d2rq-docker/editor/index.php#l45).

Problem is the static IP address, which will differ from system to system.

So we have to edit the index.php file to set the correct IP address at starting time of the d2rq docker container.

**Comment by white-gecko** [comment]
I think it would be good practice to use a configuration in this case.
But further if you are in a docker environment you can also assume specified hostnames/aliases, which you set during the linking process.

e.g. for `docker run --name ontowiki --link virtuosocontainer:triplestore`
within the `ontowiki` container the `virtuosocontainer` is available using the hostname `triplestore`, eg you could reach a sparql endpoint through `http://triplestore:8890/sparql`.
